name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  unit-tests:
    uses: ./.github/workflows/reusable-build-dotnet.yml
    with:
      configuration: Debug
      workloads: 'maui'

  android-e2e:
    needs: unit-tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET & MAUI
      uses: ./.github/actions/setup-dotnet-maui
      with:
        workloads: 'maui-android'

    - name: Setup Maestro
      uses: ./.github/actions/setup-maestro

    - name: Enable KVM
      run: |
        echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
        sudo udevadm control --reload-rules
        sudo udevadm trigger --name-match=kvm

    - name: Run Android Emulator and Maestro
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 33
        target: default
        arch: x86_64
        emulator-boot-timeout: 1200
        emulator-options: -no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim -camera-back none -no-metrics
        script: |
          chmod +x scripts/run-android-e2e.sh
          ./scripts/run-android-e2e.sh

    - name: Upload Maestro Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: maestro-report-android
        path: ~/.maestro/tests/**/*

  ios-e2e:
    needs: unit-tests
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v4

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "26.0.x"

      - name: Setup .NET & MAUI
        uses: ./.github/actions/setup-dotnet-maui
        with:
          workloads: 'maui-ios'

      - name: Setup Maestro
        uses: ./.github/actions/setup-maestro

      - name: Run iOS E2E Tests
        run: |
          chmod +x scripts/run-ios-e2e.sh
          ./scripts/run-ios-e2e.sh

      - name: Upload Maestro Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: maestro-report-ios
          path: ~/.maestro/tests/**/*

  frontend-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'
          cache-dependency-path: src/TheButton.Web/package-lock.json

      - name: Install Dependencies
        run: npm ci
        working-directory: src/TheButton.Web

      - name: Run Frontend Tests
        run: npm test
        working-directory: src/TheButton.Web
